# Generated by Django 5.1.6 on 2025-03-01 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_created_by_expense_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringexpense',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recurring Expense', 'verbose_name_plural': 'Recurring Expenses'},
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='expense',
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='title',
            field=models.CharField(default='Untitled Recurring Expense', max_length=200),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
