# Generated by Django 5.1.6 on 2025-03-01 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_avatar_alter_profile_pin'),
        ('expenses', '0003_alter_recurringexpense_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringexpense',
            options={},
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='start_date',
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='next_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
