# Generated by Django 5.1.7 on 2025-03-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_projectfinancialsummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('COMPANY', 'Company Main Account'), ('PROJECT', 'Project Account')], max_length=20),
        ),
    ]
