# Generated by Django 5.1.7 on 2025-03-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_account_account_type'),
        ('projects', '0002_auto_20250314_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectfinancialsummary',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxes', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='projects.project'),
        ),
    ]
