# Generated by Django 5.1.6 on 2025-03-05 12:39

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('DATABASE', 'Database'), ('API', 'API'), ('CSV', 'CSV File')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_string', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('api_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_format', models.CharField(blank=True, choices=[('JSON', 'JSON'), ('XML', 'XML')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('has_header', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('BANKING', 'Banking'), ('SALES', 'Sales'), ('EXPENSES', 'Expenses'), ('CLIENTS', 'Clients'), ('CUSTOM', 'Custom')], max_length=20)),
                ('time_range', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom Range')], default='MONTHLY', max_length=20)),
                ('chart_type', models.CharField(choices=[('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart'), ('DOUGHNUT', 'Doughnut Chart'), ('RADAR', 'Radar Chart'), ('POLAR', 'Polar Area Chart')], default='BAR', max_length=20)),
                ('filters', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('is_favorite', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=10)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField()),
                ('recipients', models.TextField(help_text='Comma-separated list of email addresses')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('format', models.CharField(blank=True, max_length=5)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='reports.reportschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_time_range', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom Range')], default='MONTHLY', max_length=20)),
                ('default_chart_type', models.CharField(choices=[('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart'), ('DOUGHNUT', 'Doughnut Chart'), ('RADAR', 'Radar Chart'), ('POLAR', 'Polar Area Chart')], default='BAR', max_length=20)),
                ('reports_per_page', models.IntegerField(default=10)),
                ('enable_caching', models.BooleanField(default=True)),
                ('cache_timeout', models.IntegerField(default=3600)),
                ('color_scheme', models.CharField(choices=[('default', 'Default'), ('pastel', 'Pastel'), ('vibrant', 'Vibrant'), ('monochrome', 'Monochrome')], default='default', max_length=20)),
                ('chart_font', models.CharField(default='Arial', max_length=50)),
                ('chart_title_size', models.IntegerField(default=18)),
                ('chart_label_size', models.IntegerField(default=14)),
                ('show_grid_lines', models.BooleanField(default=True)),
                ('show_legends', models.BooleanField(default=True)),
                ('legend_position', models.CharField(default='top', max_length=10)),
                ('api_token', models.CharField(blank=True, max_length=64)),
                ('api_rate_limit', models.IntegerField(default=100)),
                ('enable_api_throttling', models.BooleanField(default=True)),
                ('require_api_auth', models.BooleanField(default=True)),
                ('default_report_access', models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10)),
                ('allow_report_sharing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin')], default='VIEWER', max_length=10)),
                ('can_create', models.BooleanField(default=False)),
                ('can_schedule', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'created_by')},
            },
        ),
    ]
