# Generated by Django 5.1.6 on 2025-03-05 20:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsettings',
            name='api_rate_limit',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='enable_api_throttling',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='require_api_auth',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='aggregate_function',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='custom_colors',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='date_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reportconfiguration',
            name='group_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='chart_type',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart'), ('DOUGHNUT', 'Doughnut Chart'), ('RADAR', 'Radar Chart'), ('POLAR', 'Polar Area Chart'), ('TABLE', 'Data Table')], default='BAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='report_type',
            field=models.CharField(choices=[('BANKING', 'Banking'), ('SALES', 'Sales'), ('EXPENSES', 'Expenses'), ('CLIENTS', 'Clients'), ('LEADS', 'Leads'), ('CUSTOM', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='color_scheme',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('PASTEL', 'Pastel'), ('VIBRANT', 'Vibrant'), ('MONOCHROME', 'Monochrome'), ('CUSTOM', 'Custom')], default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='default_chart_type',
            field=models.CharField(choices=[('BAR', 'Bar Chart'), ('LINE', 'Line Chart'), ('PIE', 'Pie Chart'), ('DOUGHNUT', 'Doughnut Chart'), ('RADAR', 'Radar Chart'), ('POLAR', 'Polar Area Chart'), ('TABLE', 'Data Table')], default='BAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsettings',
            name='legend_position',
            field=models.CharField(choices=[('TOP', 'Top'), ('RIGHT', 'Right'), ('BOTTOM', 'Bottom'), ('LEFT', 'Left')], default='RIGHT', max_length=10),
        ),
    ]
