# Generated by Django 5.1.5 on 2025-02-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_remove_document_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions for the quote'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.quote')),
            ],
        ),
    ]
