# Generated by Django 5.1.5 on 2025-02-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_quote_pdf_file_quote_terms_quoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.quote'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
