# Generated by Django 5.1.5 on 2025-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_quote_quoteitem_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('SUPPLIES', 'Office Supplies'), ('EQUIPMENT', 'Equipment'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SALARY', 'Salary'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenditure_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
