# Generated by Django 5.1.5 on 2025-02-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0006_alter_document_options_document_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('QUOTE', 'Quote'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('DELIVERY_NOTE', 'Delivery Note'), ('PROFORMA_INVOICE', 'Proforma Invoice'), ('PAYMENT_RECEIPT', 'Payment Receipt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
