# Generated by Django 5.1.5 on 2025-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_document_title_document_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('QUOTE', 'Quote'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('DELIVERY_NOTE', 'Delivery Note'), ('PROFORMA_INVOICE', 'Proforma Invoice'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('SALES_RECEIPT', 'Sales Receipt')], max_length=20),
        ),
    ]
