# Generated by Django 5.1.6 on 2025-03-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='documents.quote'),
        ),
    ]
