# Generated by Django 5.1.7 on 2025-03-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_event_attendees'),
        ('communication', '0002_telebird_compat'),
    ]

    operations = [
    ]
