# Generated by Django 5.1.7 on 2025-04-04 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_merge_0002_alter_event_attendees_0002_telebird_compat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('telebird', 'Telebird'), ('yahoo', 'Yahoo'), ('custom', 'Custom SMTP')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_email_interface', models.CharField(choices=[('basic', 'Basic'), ('telebird', 'Telebird')], default='basic', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
