# Generated by Django 5.1.6 on 2025-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
