# Generated by Django 5.1.7 on 2025-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_avatar_alter_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
