"""
URL configuration for crm_leads project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

def landing_page(request):
    return render(request, 'landing.html')

def register_company(request):
    return render(request, 'company_registration.html')

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('register/', register_company, name='register_company'),
    path('admin/', admin.site.urls),
    # Include authentication URLs
    path('auth/', include('authentication.urls')),
    # Include all app URLs used in the sidebar
    path('dashboard/', include('dashboard.urls')),
    path('people/', include('people.urls')),
    path('clients/', include('clients.urls')),
    path('leads/', include('leads.urls')),
    path('project_management/', include('project_management.urls')),
    path('products/', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('purchases/', include('purchases.urls')),
    path('expenses/', include('expenses.urls')),
    path('banking/', include('banking.urls')),
    path('documents/', include('documents.urls')),
    path('reports/', include('reports.urls')),
    path('site_admin/', include('site_admin.urls')),
    # Registration URLs
    path('registration/', include('registration.urls', namespace='registration')),
    path('communication/', include('communication.urls')),  # Add communication app URLs
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
