"""
URL configuration for crm_leads project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    # Dashboard URL as root
    path('', include('dashboard.urls')),
    
    # Authentication URLs
    path('auth/', include('authentication.urls')),
    
    # Admin URL
    path('admin/', admin.site.urls),
    
    # Site Admin URL
    path('site-admin/', include('site_admin.urls')),
    
    # App URLs
    path('clients/', include('clients.urls')),
    path('projects/', include('project_management.urls')),
    path('leads/', include('leads.urls')),
    path('products/', include('products.urls')),
    path('purchases/', include('purchases.urls')),
    path('sales/', include('sales.urls')),
    path('documents/', include('documents.urls')),
    path('expenses/', include('expenses.urls')),
    path('banking/', include('banking.urls')),
    path('reports/', include('reports.urls')),
    path('access-control/', include('access_control.urls')),
    path('people/', include('people.urls')),
    path('registration/', include('registration.urls')),
    # Add redirect from /dashboard/ to root
    path('dashboard/', RedirectView.as_view(url='/', permanent=True)),
    
    # Test URLs
    path('dark-mode-test/', views.dark_mode_test, name='dark_mode_test'),
] 

# Add static and media file serving in development mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
