# Generated by Django 5.1.5 on 2025-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_amount_remove_sale_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
