# Generated by Django 5.1.5 on 2025-02-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='include_tax',
            field=models.BooleanField(default=True, verbose_name='Include VAT'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
    ]
